### ISSUE TITLE
Show Heart Rate

### ISSUE THREAD

**Issue by Hofei90** [grafana/strava-datasource#12]
Can the heart rate also be displayed in Grafana?
If this is not yet possible, I would like to make this suggestion that Strava's heart rate is also read out to Grafana.

So that the minimum, average and maximum heart rate can be displayed for the individual activities.

A detailed view of the individual activities would be difficult to implement in Grafana.

**Comment by ampujl** [comment]
This is really needed, heart rate is comming from Strava API (as many other data also) but not mapped to table data (or any other)

**Comment by ntblade** [comment]
I agree, please enable to pull all metrics. That would be fantastic
