### ISSUE TITLE
Strava datasource plugin does not show in Grafana 7.0

### ISSUE THREAD

**Issue by mgmart** [grafana/strava-datasource#14]
Hi,

got it working with 6.5 but in 7.0 it does not show up. 
Is this repo still maintained?

Cheers
Mario

**Comment by alexanderzobnin** [comment]
Yes, we fixed it, but haven't released yet. We'll try to do it this next week or so.

**Comment by OrbitMD** [comment]
awesome... keeping an eye on this.

**Comment by mvenzi** [comment]
Waiting for the solution too
;)

**Comment by sa1ntik** [comment]
The same ;)

**Comment by tsoe77** [comment]
looking forward to the new release!

**Comment by chr0me-sh** [comment]
Also can't configure the data source at the moment. Hopefully we see a fix soon :)

**Comment by andersonz1** [comment]
me too ... not working here

**Comment by andersonz1** [comment]
Any prevision to fix it ?
Error: Minified React error #130;

**Comment by flotwig** [comment]
Are there instructions for installing from Git? I was able to `make build` and `make dist` locally, but can't figure out how to install the built package in Grafana.

**Comment by OrbitMD** [comment]
just checking in again... looking forward to the new release.

**Comment by Chrisblueeyes83** [comment]
...or is it dead?

**Comment by jobenvil** [comment]
@alexanderzobnin please close the thread when you release the new version. Thanks

**Comment by sa1ntik** [comment]
> Yes, we fixed it, but haven't released yet. We'll try to do it this next week or so.

Hi Alexander, any news?

**Comment by Spinks90** [comment]
Any update? I'm using Grafana v7.1.5 and still not working.

**Comment by mgmart** [comment]
> Yes, we fixed it, but haven't released yet. We'll try to do it this next week or so.

Despite the statement above, the repo seems to be dead.

**Comment by knubbl1983** [comment]
There is a pull request for using Strava Datasource on current Grafana

https://github.com/grafana/strava-datasource/issues/14

**Comment by flotwig** [comment]
@knubbl1983 did you mean to link to #20 ? have you tried that PR with 7.0? i tried the current `master` branch on 7.0 but ran into [issues](https://github.com/grafana/strava-datasource/issues/14#issuecomment-648172782), haven't tried #20  yet

**Comment by knubbl1983** [comment]
@flotwig yes the #20 ..i havent tried this yet cause im not that familiar with git and install a pull request manually. maybe u can give me some hints for that so i will try the PR

**Comment by linusg** [comment]
@alexanderzobnin any chance the release could happen soon? It's sad to have this great datasource broken in Grafana 7 for so long, for basically no reason :(

**Comment by cjander** [comment]
joining the thread. I see some activity on pr's but still no new release @alexanderzobnin any update?

**Comment by alexanderzobnin** [comment]
We're working on some refactoring/small improvements. We haven't a lot of time for this work, but we'll try to release as soon as PR's will be tested and merged.

**Comment by alexanderzobnin** [comment]
Ok, next version (1.2.0) finally released, so closing this.
