### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by Chrisblueeyes83** [grafana/strava-datasource#2]
i try to connect to strava but get always an error.
{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

**Comment by tjmoore** [comment]
I found that the website URL specified in Strava API settings *must* be the same as the URL of your grafana instance, even if it's a local URL or IP address. Including port number.

e.g. http://mygrafana:3000

When it redirects back, follow the rest of the config instructions to fill in the Client ID and secret, then click Fill, then save & test. Don't click off the page until then as it needs the information in the URL from the redirect.

I'm stuck though on the dashboards. I get loads of errors on the import dashboards.

**Comment by Chrisblueeyes83** [comment]
hm. that doesnt work for me. im still getting this error.

**Comment by alexanderzobnin** [comment]
Yes, unfortunately, Strava changed API recently (actually, it looks like they just fixed a bug that allowed to use auth code multiple times), so plugin doesn't work properly now. We're going to fix it soon, so stay in touch.

**Comment by gunarg** [comment]
I'm unable to to connect to strava using "Data Sources / Strava" how can i proof that this is related to this bug?
"Connect with Strava" button works and i can reset and fill new "Auth Code"
"Save & Test" returnes:  "Cannot connect to Strava API"
