### ISSUE TITLE
Can't add data source on Grafana Cloud / plugin Strava

### ISSUE THREAD

**Issue by mschindl** [grafana/strava-datasource#25]
![image](https://user-images.githubusercontent.com/26382876/95425863-3fa36b80-0945-11eb-8ec8-7f9cfd32e7b7.png)
![image](https://user-images.githubusercontent.com/26382876/95425889-4cc05a80-0945-11eb-8aa7-ebb64d8358ca.png)

**Comment by knubbl1983** [comment]
i still cant add strava datsource to new sources. i updates from current sources and still there is no strava data source .

any idea what i can check

**Comment by cryptobobdole** [comment]
I am also having this issue, but with Grafana hosted on my own machine.

**Comment by alexanderzobnin** [comment]
Hi! Try to upgrade plugin to 1.2.0, probably, it's a compatibility issue.

**Comment by fcspiteri** [comment]
I'm able to install 1.2.0 but can't configure. When I add Client ID and click "Connect with Strava" I get this error message:

`{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}`

**Comment by sa1ntik** [comment]
> I am also having this issue, but with Grafana hosted on my own machine.

if you still have this issue, try to add the plugin name “grafana-strava-datasource” to the allow_loading_unsigned_plugins variable In /etc/grafana/grafana.ini (around line 696) and restart Grafana

**Comment by alexanderzobnin** [comment]
> if you still have this issue, try to add the plugin name “grafana-strava-datasource” to the allow_loading_unsigned_plugins variable In /etc/grafana/grafana.ini (around line 696) and restart Grafana

You don't need to do this anymore - plugin is signed now.
