### ISSUE TITLE
Failed  to local build on win10 -- powershell

### ISSUE THREAD

**Issue by yihong0618** [grafana/strava-datasource#30]
Hi ~
![image](https://user-images.githubusercontent.com/15976103/106552061-8ac73700-6551-11eb-9957-b135df47570d.png)

![image](https://user-images.githubusercontent.com/15976103/106552094-9ca8da00-6551-11eb-8560-2c6554aa9009.png)

I Searched and found it seems this problem see https://github.com/grafana/grafana-plugin-sdk-go/pull/184/files/01d83efaf4c011aea16a698acd4443e1808c4caa

And I try to fix  like this pr, but it shows `undefinedunix.Kill`

Thank you

**Comment by yihong0618** [comment]
If you want build on win10.

You can just change `Magefile.go` to
```golang
//+build mage

package main

import (
	// mage:import
	build "github.com/grafana/grafana-plugin-sdk-go/build"
)

// Default configures the default target.
var Default = build.BuildAl
```
Then `mage -v`

**Comment by alexanderzobnin** [comment]
Hi! Could you open a PR with these changes?

**Comment by yihong0618** [comment]
> Hi! Could you open a PR with these changes?

Of course,  will open a `PR` latter today.
