### ISSUE TITLE
connection problems 

### ISSUE THREAD

**Issue by Chrisblueeyes83** [grafana/strava-datasource#4]
the connection problems stays.
i´m getting this error:
{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

**Comment by alexanderzobnin** [comment]
@Chrisblueeyes83 Hi! Make sure your _Authorization Callback Domain_ at Strava app page meets your grafana instance domain.

**Comment by Chrisblueeyes83** [comment]
I have my grafana local on a Intel NUC running, so is it not possible to connect?

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Alexander Zobnin <notifications@github.com>
Gesendet: Dienstag, 10. März 2020 11:05
An: grafana/strava-datasource
Cc: Chrisblueeyes83; Mention
Betreff: Re: [grafana/strava-datasource] connection problems (#4)


@Chrisblueeyes83<https://github.com/Chrisblueeyes83> Hi! Make sure your Authorization Callback Domain at Strava app page meets your grafana instance domain.

**Comment by alexanderzobnin** [comment]
It doesn't matter I think. The only requirement is matched domain. So if you access grafana with `http://grafana.my.domain.com`, set _Authorization Callback Domain_ to `grafana.my.domain.com`.

**Comment by Chrisblueeyes83** [comment]
I did it like you said, but always the error appears:
{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

**Comment by alexanderzobnin** [comment]
`"code":"invalid"` means authorization code obtained from Strava (you can see it in the url as a `code` param) is not valid or was used more than one time. Do you use latest plugin version (`1.1.1`)?

**Comment by Chrisblueeyes83** [comment]
Yes, I use the latest version. Can I reset the code?

Sent from Nine<http://www.9folders.com/>
________________________________
Von: Alexander Zobnin <notifications@github.com>
Gesendet: Dienstag, 10. März 2020 11:50
An: grafana/strava-datasource
Cc: Chrisblueeyes83; Mention
Betreff: Re: [grafana/strava-datasource] connection problems (#4)


"code":"invalid" means authorization code obtained from Strava (you can see it in the url as a code param) is not valid or was used more than one time. Do you use latest plugin version (1.1.1)?

**Comment by alexanderzobnin** [comment]
Yes, click _Connect with Strava_ button to obtain new code from Strava.

**Comment by Chrisblueeyes83** [comment]
i tried it many times, but it did not work. always the same error message.

**Comment by alexanderzobnin** [comment]
Could you post your Strava app config?

**Comment by Chrisblueeyes83** [comment]
![image](https://user-images.githubusercontent.com/60074430/76329048-57057200-62ec-11ea-81b1-16506e995064.png)

**Comment by alexanderzobnin** [comment]
And could you also post redirect URI from page where you get error, like:
```
https://www.strava.com/oauth/authorize?client_id=12345&response_type=code&redirect_uri=http://wrong.grafana-zabbix.org/datasources/edit/1/&approval_prompt=force&scope=read_all,profile:read_all,activity:read_all
```

**Comment by Chrisblueeyes83** [comment]
https://www.strava.com/oauth/authorize?client_id=42718&response_type=code&redirect_uri=http://192.168.1.225:3000/datasources/edit/21/&approval_prompt=force&scope=read_all,profile:read_all,activity:read_all

**Comment by Chrisblueeyes83** [comment]
(https://www.strava.com/oauth/authorize?client_id=42718&response_type=code&redirect_uri=http://192.168.1.225:3000/datasources/edit/21/&approval_prompt=force&scope=read_all,profile:read_all,activity:read_all)

**Comment by alexanderzobnin** [comment]
But in your URI `redirect_uri` doesn't match your domain in strava app.

**Comment by Chrisblueeyes83** [comment]
i see, but why?

**Comment by alexanderzobnin** [comment]
Do you access your grafana by `grafana.boehm-folien.at` or `192.168.1.225`?

**Comment by Chrisblueeyes83** [comment]
i tried it first with 192.... then grafana.boehm-folien.at  no difference, always the same error

**Comment by alexanderzobnin** [comment]
Try using `192.168.1.225:3000`.

**Comment by Chrisblueeyes83** [comment]
didnt work. i tried almost any configuration

**Comment by alexanderzobnin** [comment]
I'm 99% sure it's because `redirect_uri` doesn't match callback domain.

**Comment by Chrisblueeyes83** [comment]
finaly, i get it working! :)

**Comment by Chrisblueeyes83** [comment]
i wrote the redirect uri with port number. that was the problem. 
![image](https://user-images.githubusercontent.com/60074430/76331012-d5fbaa00-62ee-11ea-963a-52b3b3a6d80b.png)
