### ISSUE TITLE
Issue with configuring Strava datasource in Grafana

### ISSUE THREAD

**Issue by Chandruind** [grafana/strava-datasource#41]
Hello All, 

im getting an error while configuring a Strava datasource in Grafana as Refresh token not available, authorize datasource first message. I tried to follow some of existing issue to understand the problem but it didnt helps as one of the recommendation given to use callback domain in strava as IP address but it didnt help. please find below Grafana logs and help me how to get it sorted. Thanks in advance. 

remote_addr=192.168.0.101 time_ms=7 size=26 referer=http://192.168.0.101:3000/login
t=2021-05-28T19:29:10+0530 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2021-05-28T19:29:39+0530 lvl=eror msg="Strava API request error" logger=plugins.backend pluginId=grafana-strava-datasource error="Auth error, status: 401 Unauthorized"
t=2021-05-28T19:29:39+0530 lvl=eror msg="Request Completed" logger=c2ontext userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/auth status=500 remote_addr=192.168.0.101 time_ms=1283 size=82 referer="http://192.168.0.101:3000/datasources/edit/1/?state=&code=7b93f555988d0f97c411872960ef05bbc4df7e5a&scope=read,activity:read_all,profile:read_all,read_all"
t=2021-05-28T19:29:39+0530 lvl=eror msg="open /1-refreshToken: The system cannot find the file specified." logger=plugins.backend pluginId=grafana-strava-datasource
t=2021-05-28T19:29:39+0530 lvl=eror msg="Strava API request error" logger=plugins.backend pluginId=grafana-strava-datasource error="Refresh token not found, authorize datasource first"
t=2021-05-28T19:29:39+0530 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/1/resources/strava-api status=500 remote_addr=192.168.0.101 time_ms=3 size=97 referer="http://192.168.0.101:3000/datasources/edit/1/?state=&code=7b93f555988d0f97c411872960ef05bbc4df7e5a&scope=read,activity:read_all,profile:read_all,read_all"

**Comment by Chandruind** [comment]
![image](https://user-images.githubusercontent.com/84977864/119999205-18da9800-bfef-11eb-94db-b019ceb43acb.png)

**Comment by sharkoz** [comment]
Have you followed the [doc](https://github.com/grafana/strava-datasource/blob/master/docs/configuration.md) ?
You need to create an app in strava first and fill in the client id and client secret provided by strava.

**Comment by Chandruind** [comment]
Yes i have configured & created an app in Strava using URL - https://www.strava.com/settings/api and i got the Client ID and Client secret and using these client ID and client secret i was trying to configure the Strava Datasource but it was giving the error as mentioned above. 

Kindly assist further

**Comment by Chandruind** [comment]
Hi, i tried once again with deleting the datasource and reconfigured again, it is working fine with no issues.. thanks for your help..

**Comment by Bedasek** [comment]
I provide both **Client ID** and **Client Secret** and when I click "Connect with STRAVA" button, I get following page -
**url**: _https://www.strava.com/oauth/authorize?client_id=54783&response_type=code&redirect_uri=https://192.168.0.99:3000/datasources/edit/BMLnhMmRz&approval_prompt=force&scope=read_all,profile:read_all,activity:read_all_

_browser headers are localizes to czech, however you get the idea from the body:_
![obrazek](https://user-images.githubusercontent.com/17751503/150653853-4e70b1a2-0604-4982-84e2-902033553c62.png)
