### ISSUE TITLE
Include Distance as Miles

### ISSUE THREAD

**Issue by Irievibesender** [grafana/strava-datasource#43]
I see that the default API brings in the data as kilometers. My Strava dashboard is setup for miles, but apparently that is only for my account and not the API data. I tried to change the data units to miles in Grafana but if I ride for instance 11.45km and this shows up on my dashboard. If i change the units to miles it will just make it 114450 miles instead of converting it over to 7.11 miles. I have not found anyway to have it display in miles thus far and wonder how those living in the US can get this to show in miles.

**Comment by Irievibesender** [comment]
![2021-06-10 22_57_23-Window](https://user-images.githubusercontent.com/85722151/121628654-3ff98680-ca3f-11eb-8c94-ff5ca2b79b14.png)
![2021-06-10 22_55_41-Window](https://user-images.githubusercontent.com/85722151/121628660-412ab380-ca3f-11eb-83d5-6373439592c5.png)

**Comment by Irievibesender** [comment]
I did find a way to add a binary transform and covert the apparently data feed meters to miles 
![image](https://user-images.githubusercontent.com/85722151/121631133-1ee76480-ca44-11eb-8f55-655e392032d3.png)

**Comment by alexanderzobnin** [comment]
I added automatic conversion based on your profile preferences.

![Screenshot from 2021-12-24 12-02-32](https://user-images.githubusercontent.com/4932851/147337904-ea462fd2-8d6b-42d3-b6d6-555c36b8ea10.png)
