### ISSUE TITLE
Grafana 8.0

### ISSUE THREAD

**Issue by digitalyours** [grafana/strava-datasource#44]
The plugin seems not to be compatible with Grafana 8.0. The "connect with Strava" button produces a 404.
Best C.

**Comment by pkolyvas** [comment]
I've gotten it to work, but it seems the authorization callback domain needs to work.

**Comment by digitalyours** [comment]
Mhm. I have my Grafana installation in a subdirectory (which worked before 8.0)...

**Comment by alexanderzobnin** [comment]
@digitalyours do you have any updates? Is it still a problem?

**Comment by digitalyours** [comment]
Thanks for asking. The issue was resolved with one of the last updates.
