### ISSUE TITLE
Single Activity Map?

### ISSUE THREAD

**Issue by beirtipol** [grafana/strava-datasource#49]
Is it possible to show the route, or even starting location for a single activity on the worldmap? I tried playing with the worldmap plugin on my datasource but just ended up blowing my request limit. Would be nice to filter through activities, clicking on a specific one to see where it was

**Comment by alexanderzobnin** [comment]
It's something I think about. We have a new [geomap panel](https://grafana.com/docs/grafana/latest/visualizations/geomap/) which is replacement for the worldmap, so I can experiment with it. Plugin already parses activity geo points, so I only need to find a way to put it into the map.

**Comment by alexanderzobnin** [comment]
It will look like this

![Screenshot from 2021-12-23 14-08-37](https://user-images.githubusercontent.com/4932851/147232609-c6f3ee48-19c2-44fc-a21c-98fc38f8b732.png)

**Comment by alexanderzobnin** [comment]
Unfortunately, there's no way to visualize path yet, but hope, it will be added sometimes. There's an epic issue (roadmap) for the geomap https://github.com/grafana/grafana/issues/36585.

**Comment by alexanderzobnin** [comment]
@beirtipol it should be possible now with latest geomap panel features. This dashboard will be in 1.5 release which coming soon.

![Screenshot from 2022-08-24 11-26-30](https://user-images.githubusercontent.com/4932851/186369461-6da735ac-a3f2-4817-b790-dba2204c3fb0.png)
