### ISSUE TITLE
Unable to connect Strava to grafana cloud

### ISSUE THREAD

**Issue by wamari** [grafana/strava-datasource#54]
I just started playing with grafana. I am running a cloud instance and sadly can't seem to connect it to Strava. I have created the app at https://www.strava.com/settings/api 
![2022-03-16 19 08 31 www strava com e2d74c9acb31](https://user-images.githubusercontent.com/6112140/158635372-da83936e-e409-4d59-afcf-56ef703be725.png)

![2022-03-16 19 04 03 wamari grafana net 60029132e2c0](https://user-images.githubusercontent.com/6112140/158634727-1c1e4716-3d7e-4ddb-b18e-1c893dac0ea5.png)

Could I be doing something wrong?

**Comment by computemarine** [comment]
I also have this problem. After setting up Strava API, I cannot get the Grafana plugin to connect to Strava. Perpetual 401 errors... I tried the default OAuth option, as well as the Refresh token option, but to no avail. Setting the Strava API Authorization Callback Domain to my Grafana instance, localhost, or anything else does not change this.

**Comment by alexanderzobnin** [comment]
That's strange. I'll try to figure it out.
