### ISSUE TITLE
Geomap and link

### ISSUE THREAD

**Issue by zolpif** [grafana/strava-datasource#78]
In a geomap, it seems impossible to link a marker of an activity to a specific activity. I tried with different layers, queries, and so on. But I can't get the ${__data.fields.id} while being in a geomap query.
Any clue? Thanks for your amazing work.

**Comment by alexanderzobnin** [comment]
Ok, seems I got it. Added more info (and also added data link to the activity dashboard) here a3f9b864627c46bd5719edcbea446dce89b0b514
